image:
  repository: ghcr.io/thedevminertv/clustertop
  pullPolicy: Always
  tag: "master"

replicas: 2

service:
  app_port: 80
  host: stats.k8s.devminer.xyz
  ssl:
    enabled: true
    port: 443
    issuer:
      name: letsencrypt
      kind: ClusterIssuer

resources:
  limits:
    cpu: 256m
    memory: 96Mi
  requests:
    cpu: 16m
    memory: 16Mi

# populated by the ArgoCD application
devhosting:
  appname: ''
